/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  //  documentationSidebar:

  documentationSidebar: [
    /// Developer Portal
    {
      type: "category",
      label: "Developer Portal",
      items: [
        {
          type: "autogenerated",
          dirName: "developer-portal", // Generate sidebar slice from docs path
        },
      ],
    },
    /// Blackboard
    {
      "Blackboard Learn": [
        "blackboard/welcome",
        /// Rest APIs
        {
          "REST APIs": [
            // Getting Started
            "blackboard/rest-apis/start-here",
            "blackboard/rest-apis/rest-api-best-practices",
            {
              type: "category",
              label: "Getting Started",

              //
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/getting-started", // Generate sidebar slice from docs path
                },
              ],
            },
            // Hands on Blackboard APIs
            {
              type: "category",
              label: "Hands on",

              //
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/hands-on", // Generate sidebar slice from docs path
                },
              ],
            },
            // Advanced
            {
              type: "category",
              label: "Advanced",

              //
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/advanced", // Generate sidebar slice from docs path
                },
              ],
            },
            // Demo code
            {
              type: "category",
              label: "Demo code",

              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/demo-code", // Generate sidebar slice from docs path
                },
              ],
            },
          ],
        },
        /// LTI
        {
          LTI: [
            "blackboard/lti/welcome",
            {
              "LTI 1.3/Advantage": [
                "blackboard/lti/1.3/register-an-application",
                {
                  "Core LTI 1.3": [
                    {
                      type: "autogenerated",
                      dirName: "blackboard/lti/1.3/core",
                    },
                  ],
                  "Deep Linking": [
                    {
                      type: "autogenerated",
                      dirName: "blackboard/lti/1.3/dl",
                    },
                  ],
                  "Grades and Roles Subsystems": [
                    "blackboard/lti/1.3/lti-subsystems/lti-sub-authentication",
                    {
                      "Assignments and Grades Service": [
                        {
                          type: "autogenerated",
                          dirName: "blackboard/lti/1.3/lti-subsystems/ags",
                        },
                      ],
                    },
                    // {
                    //   "Names and Roles Provisioning Service": [
                    //     {
                    //       type: "autogenerated",
                    //       dirName: "blackboard/lti/1.3/lti-subsystems/nrps",
                    //     },
                    //   ],
                    // },
                  ],
                },
                "blackboard/lti/1.3/best-practices",
              ],
              // "Legacy LTI 1.1": [
              //   {
              //     type: "autogenerated",
              //     dirName: "blackboard/lti/1.1",
              //   },
              // ],
            },
          ],
        },
        /// UEF
        {
          "Ultra Extension Framework (UEF)": [
            {
              type: "autogenerated",
              dirName: "blackboard/uef",
            },
            {
              type: "link",
              label: "UEF specifications",
              href: "https://docs.anthology.com/uef-documentation/start.html",
            },
          ],
        },
        /// Proctoring
        {
          Proctoring: [
            {
              type: "autogenerated",
              dirName: "blackboard/proctoring",
            },
          ],
        },
        /// Standards
        {
          Caliper: [
            "blackboard/caliper/getting-started",
            "blackboard/caliper/event-store-in-learn",
            "blackboard/caliper/metric-profiles",
            {
              Events: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/caliper/events",
                },
              ],
            },
          ],
        },
        "developer-ami",
        "developer-amifromvmdk",
      ],
    },
    // Student
    {
      type: "category",
      label: "Student",

      //
      items: [
        {
          type: "category",
          label: "Getting Started",

          items: [
            {
              type: "autogenerated",
              dirName: "student/getting-started", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Best Practices",

          items: [
            {
              type: "autogenerated",
              dirName: "student/best-practices", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Service Catalog",

          items: [
            {
              type: "autogenerated",
              dirName: "student/service-catalog", // Generate sidebar slice from docs path
            },
            {
              type: "link",
              label: "Log into My Campus Insight ",
              href: "https://www.mycampusinsight.com/_layouts/CampusManagement/login.aspx?ReturnUrl=%2f_layouts%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F",
            },
          ],
        },
      ],
    },
    // Ally
    {
      type: "category",
      label: "Ally",

      //
      items: [
        {
          type: "autogenerated",
          dirName: "ally", // Generate sidebar slice from docs path
        },
      ],
    },
    // Partners
    {
      type: "category",
      label: "Partners",

      //
      items: [
        {
          type: "autogenerated",
          dirName: "partners", // Generate sidebar slice from docs path
        },
      ],
    },
    // Community
    {
      type: "category",
      label: "Community",

      //
      items: [
        {
          type: "autogenerated",
          dirName: "community", // Generate sidebar slice from docs path
        },
      ],
    },
    "maintenance-page",
  ],
};

module.exports = sidebars;
