/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  //  documentationSidebar:

  documentationSidebar: [
    "site-intro",
    {
      type: "category",
      label: "Developer Portal",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "developer-portal", // Generate sidebar slice from docs path
        },
      ],
    },
    // REST APIs
    {
      type: "category",
      label: "REST APIs",
      collapsible: true,
      collapsed: true,
      items: [
        "rest-apis/start-here",
        // Learn
        {
          type: "category",
          label: "Learn",
          collapsible: true,
          // collapsed: true,
          items: [
            "rest-apis/learn/learn-intro",
            // Getting Started
            {
              type: "category",
              label: "Getting Started",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/learn/getting-started", // Generate sidebar slice from docs path
                },
              ],
            },
            // Admin
            {
              type: "category",
              label: "Admin",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/learn/admin", // Generate sidebar slice from docs path
                },
              ],
            },
            // Working with Learn APIs
            {
              type: "category",
              label: "Working with Learn APIs",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/learn/working-with-learn-apis", // Generate sidebar slice from docs path
                },
              ],
            },
            // Examples
            {
              type: "category",
              label: "Examples",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/learn/examples", // Generate sidebar slice from path
                },
              ],
            },
            // Advanced
            {
              type: "category",
              label: "Advanced",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/learn/advanced", // Generate sidebar slice from docs path
                },
              ],
            },
            // Sandbox
            {
              type: "category",
              label: "Sandbox",
              collapsible: true,
              // collapsed: true,
              items: ["rest-apis/learn/sandbox/developer-ami"],
            },
            // Learn App
            {
              type: "category",
              label: "Learn App",
              collapsible: true,
              // collapsed: true,
              items: ["rest-apis/learn/learn-app/student-launch-schema"],
            },
          ],
        },
        // Ally
        {
          type: "category",
          label: "Ally",
          collapsible: true,
          // collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "rest-apis/ally", // Generate sidebar slice from docs path
            },
          ],
        },
        // Student
        {
          type: "category",
          label: "Student",
          collapsible: true,
          // collapsed: true,
          items: [
            {
              type: "category",
              label: "Getting Started",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/student/getting-started", // Generate sidebar slice from docs path
                },
              ],
            },
            {
              type: "category",
              label: "Service Catalog",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "rest-apis/student/service-catalog", // Generate sidebar slice from docs path
                },
                {
                  type: "link",
                  label: "Log into My Campus Insight ",
                  href: "https://www.mycampusinsight.com/_layouts/CampusManagement/login.aspx?ReturnUrl=%2f_layouts%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F",
                },
              ],
            },
            // {
            //   type: 'category',
            //   label: 'Examples',
            //   collapsible: true,
            //   items: [
            //     {
            //       type: 'autogenerated',
            //       dirName: 'REST APIs/Student/Examples', // Generate sidebar slice from docs path
            //     },
            //   ]
            // },
            // {
            //   type: 'category',
            //   label: 'Tutorials',
            //   collapsible: true,
            //   items: [
            //     'REST APIs/Student/tutorials/student-training-videos'
            //   ]
            // },
          ],
        },
        // Premium APIs
        {
          type: "category",
          label: "Premium APIs",
          collapsible: true,
          // collapsed: true,
          items: [
            "rest-apis/premium-apis/requesting-premium-apis",
            {
              type: "category",
              label: "UEF",
              collapsible: true,
              items: [
                "rest-apis/premium-apis/uef/getting-started",
                {
                  type: "autogenerated",
                  dirName: "rest-apis/premium-apis/uef/tutorials", // Generate sidebar slice from docs path
                },
                {
                  type: "link",
                  label: "UEF Documentation",
                  href: "https://docs.anthology.com/uef-documentation/start.html",
                },
              ],
            },
            // {
            //   type: 'autogenerated',
            //   dirName: 'REST APIs/Premium APIs', // Generate sidebar slice from docs path
            // },
          ],
        },
      ],
    },
    // LTI
    {
      type: "category",
      label: "LTI",
      collapsible: true,
      // collapsed: true,
      items: [
        "lti/introduction",
        "lti/getting-started-with-lti",
        "lti/lti-registration-deployment",
        "lti/registration-deployment",
        "lti/lti-deep-linking",
        "lti/turn-on-all-switches",
        {
          type: "category",
          label: "Core",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "lti/core", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Migrating",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "lti/migrating", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Proctoring",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "lti/proctoring", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Tutorials",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "lti/tutorials", // Generate sidebar slice from docs path
            },
          ],
        },
      ],
    },
    // Standards
    {
      type: "category",
      label: "Standards",
      collapsible: true,
      // collapsed: true,
      items: [
        "standards/standards-intro",
        {
          type: "category",
          label: "Caliper",
          collapsible: true,
          items: [
            // 'Standards/Caliper/caliper-intro',
            {
              type: "category",
              label: "Getting Started",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "standards/caliper/getting-started", // Generate sidebar slice from docs path
                },
              ],
            },
            {
              type: "category",
              label: "Events",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "standards/caliper/events", // Generate sidebar slice from docs path
                },
              ],
            },
          ],
        },
      ],
    },
    // Partners
    {
      type: "category",
      label: "Partners",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "partners", // Generate sidebar slice from docs path
        },
      ],
    },
    // Community
    {
      type: "category",
      label: "Community",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "community", // Generate sidebar slice from docs path
        },
      ],
    },
  ],
};

module.exports = sidebars;
