/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  //  documentationSidebar:

  documentationSidebar: [
    {
      // Developer Portal
      type: "category",
      label: "Developer Portal",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "developer-portal", // Generate sidebar slice from docs path
        },
      ],
    },
    // Blackboard
    {
      type: "category",
      label: "Blackboard Learn",
      collapsible: true,
      collapsed: true,
      items: [
        "blackboard/rest-apis/start-here",
        "blackboard/rest-apis/rest-api-best-practices",
        // Rest APIs
        {
          type: "category",
          label: "REST APIs",
          collapsible: true,
          // collapsed: true,
          items: [
            // Getting Started
            {
              type: "category",
              label: "Getting Started",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/getting-started", // Generate sidebar slice from docs path
                },
              ],
            },
            // Hands on Blackboard APIs
            {
              type: "category",
              label: "Hands on",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/hands-on", // Generate sidebar slice from docs path
                },
              ],
            },
            // Advanced
            {
              type: "category",
              label: "Advanced",
              collapsible: true,
              // collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/advanced", // Generate sidebar slice from docs path
                },
              ],
            },
            // Demo code
            {
              type: "category",
              label: "Demo code",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/rest-apis/demo-code", // Generate sidebar slice from docs path
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "LTI",
          collapsible: true,
          // collapsed: true,
          items: [
            "blackboard/lti/introduction",
            "blackboard/lti/getting-started-with-lti",
            "blackboard/lti/lti-registration-deployment",
            "blackboard/lti/registration-deployment",
            "blackboard/lti/lti-deep-linking",
            "blackboard/lti/turn-on-all-switches",
            {
              type: "category",
              label: "Core",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/lti/core", // Generate sidebar slice from docs path
                },
              ],
            },
            {
              type: "category",
              label: "Migrating",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/lti/migrating", // Generate sidebar slice from docs path
                },
              ],
            },
            {
              type: "category",
              label: "Proctoring",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/lti/proctoring", // Generate sidebar slice from docs path
                },
              ],
            },
            {
              type: "category",
              label: "Tutorials",
              collapsible: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "blackboard/lti/tutorials", // Generate sidebar slice from docs path
                },
              ],
            },
          ],
        },
        // Premium APIs
        {
          type: "category",
          label: "Premium APIs",
          collapsible: true,
          // collapsed: true,
          items: [
            "blackboard/premium-apis/requesting-premium-apis",
            {
              type: "category",
              label: "UEF",
              collapsible: true,
              items: [
                "blackboard/premium-apis/uef/getting-started",
                {
                  type: "autogenerated",
                  dirName: "blackboard/premium-apis/uef/tutorials", // Generate sidebar slice from docs path
                },
                {
                  type: "link",
                  label: "UEF Documentation",
                  href: "https://docs.anthology.com/uef-documentation/start.html",
                },
              ],
            },
          ],
        },
        "developer-ami",
      ],
    },
    // Student
    {
      type: "category",
      label: "Student",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "category",
          label: "Getting Started",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "student/getting-started", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Best Practices",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "student/best-practices", // Generate sidebar slice from docs path
            },
          ],
        },
        {
          type: "category",
          label: "Service Catalog",
          collapsible: true,
          items: [
            {
              type: "autogenerated",
              dirName: "student/service-catalog", // Generate sidebar slice from docs path
            },
            {
              type: "link",
              label: "Log into My Campus Insight ",
              href: "https://www.mycampusinsight.com/_layouts/CampusManagement/login.aspx?ReturnUrl=%2f_layouts%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F",
            },
          ],
        },
      ],
    },
    // Ally
    {
      type: "category",
      label: "Ally",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "ally", // Generate sidebar slice from docs path
        },
      ],
    },
    // Partners
    {
      type: "category",
      label: "Partners",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "partners", // Generate sidebar slice from docs path
        },
      ],
    },
    // Community
    {
      type: "category",
      label: "Community",
      collapsible: true,
      // collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "community", // Generate sidebar slice from docs path
        },
      ],
    },
    "maintenance-page",
  ],
};

module.exports = sidebars;
